### ISSUE TITLE
Final takvimi cekme

### ISSUE THREAD

**Issue by evinpinar** [triforce930/bounScheduleToCalendar#3]
- Final takvimi belli olunca onu da calendar'a ceken birsey olabilir
- belli oldugunda alarm verebilir
- notlar aciklandiginda falan alarm verebilir

**Comment by karacasoft** [comment]
Alarm verme kısmı bu programın çalışma şekline aykırı bi durum. O kısım ancak birinin bu kodu alıp anlık kontrol yapan bi uygulamaya dönüştürmesiyle mümkün. Bunu yapmaları için zaten LGPL 3.0 lisansını kullandım.

Final takviminin bulunduğu sayfanın kullanılmasıyla 1. öneri yapılabilir görünüyor. Bunu sonra incelemek üzere bu issue'yu kapatıyorum.
